"""
attack_lookup.py — MITRE ATT&CK 기법 ID → (이름, 전술) 정적 조회 테이블

CAPA / VirusTotal 등 외부 도구에서 기법 ID만 반환될 때 이름·전술을 보완합니다.
ATT&CK v14 기준 주요 Windows 관련 기법 포함.
"""
from __future__ import annotations

# technique_id → (technique_name, tactic)
_LOOKUP: dict[str, tuple[str, str]] = {
    # ── Reconnaissance ────────────────────────────────────────────────
    "T1595":     ("Active Scanning", "Reconnaissance"),
    "T1592":     ("Gather Victim Host Information", "Reconnaissance"),
    "T1589":     ("Gather Victim Identity Information", "Reconnaissance"),
    "T1590":     ("Gather Victim Network Information", "Reconnaissance"),
    # ── Resource Development ──────────────────────────────────────────
    "T1583":     ("Acquire Infrastructure", "Resource Development"),
    "T1588":     ("Obtain Capabilities", "Resource Development"),
    "T1587":     ("Develop Capabilities", "Resource Development"),
    # ── Initial Access ────────────────────────────────────────────────
    "T1566":     ("Phishing", "Initial Access"),
    "T1566.001": ("Phishing: Spearphishing Attachment", "Initial Access"),
    "T1566.002": ("Phishing: Spearphishing Link", "Initial Access"),
    "T1566.003": ("Phishing: Spearphishing via Service", "Initial Access"),
    "T1190":     ("Exploit Public-Facing Application", "Initial Access"),
    "T1133":     ("External Remote Services", "Initial Access"),
    "T1091":     ("Replication Through Removable Media", "Initial Access"),
    "T1195":     ("Supply Chain Compromise", "Initial Access"),
    "T1200":     ("Hardware Additions", "Initial Access"),
    "T1078":     ("Valid Accounts", "Initial Access"),
    # ── Execution ─────────────────────────────────────────────────────
    "T1059":     ("Command and Scripting Interpreter", "Execution"),
    "T1059.001": ("Command and Scripting Interpreter: PowerShell", "Execution"),
    "T1059.002": ("Command and Scripting Interpreter: AppleScript", "Execution"),
    "T1059.003": ("Command and Scripting Interpreter: Windows Command Shell", "Execution"),
    "T1059.005": ("Command and Scripting Interpreter: Visual Basic", "Execution"),
    "T1059.006": ("Command and Scripting Interpreter: Python", "Execution"),
    "T1059.007": ("Command and Scripting Interpreter: JavaScript", "Execution"),
    "T1106":     ("Native API", "Execution"),
    "T1053":     ("Scheduled Task/Job", "Execution"),
    "T1053.005": ("Scheduled Task/Job: Scheduled Task", "Execution"),
    "T1047":     ("Windows Management Instrumentation", "Execution"),
    "T1204":     ("User Execution", "Execution"),
    "T1204.001": ("User Execution: Malicious Link", "Execution"),
    "T1204.002": ("User Execution: Malicious File", "Execution"),
    "T1569":     ("System Services", "Execution"),
    "T1569.002": ("System Services: Service Execution", "Execution"),
    "T1129":     ("Shared Modules", "Execution"),
    "T1072":     ("Software Deployment Tools", "Execution"),
    "T1559":     ("Inter-Process Communication", "Execution"),
    "T1559.001": ("Inter-Process Communication: Component Object Model", "Execution"),
    "T1559.002": ("Inter-Process Communication: Dynamic Data Exchange", "Execution"),
    # ── Persistence ───────────────────────────────────────────────────
    "T1547":     ("Boot or Logon Autostart Execution", "Persistence"),
    "T1547.001": ("Boot or Logon Autostart Execution: Registry Run Keys / Startup Folder", "Persistence"),
    "T1547.002": ("Boot or Logon Autostart Execution: Authentication Package", "Persistence"),
    "T1547.004": ("Boot or Logon Autostart Execution: Winlogon Helper DLL", "Persistence"),
    "T1547.005": ("Boot or Logon Autostart Execution: Security Support Provider", "Persistence"),
    "T1547.009": ("Boot or Logon Autostart Execution: Shortcut Modification", "Persistence"),
    "T1547.012": ("Boot or Logon Autostart Execution: Print Processors", "Persistence"),
    "T1543":     ("Create or Modify System Process", "Persistence"),
    "T1543.003": ("Create or Modify System Process: Windows Service", "Persistence"),
    "T1546":     ("Event Triggered Execution", "Persistence"),
    "T1546.001": ("Event Triggered Execution: Change Default File Association", "Persistence"),
    "T1546.007": ("Event Triggered Execution: Netsh Helper DLL", "Persistence"),
    "T1546.009": ("Event Triggered Execution: AppCert DLLs", "Persistence"),
    "T1546.010": ("Event Triggered Execution: AppInit DLLs", "Persistence"),
    "T1546.011": ("Event Triggered Execution: Application Shimming", "Persistence"),
    "T1546.012": ("Event Triggered Execution: Image File Execution Options Injection", "Persistence"),
    "T1136":     ("Create Account", "Persistence"),
    "T1136.001": ("Create Account: Local Account", "Persistence"),
    "T1574":     ("Hijack Execution Flow", "Persistence"),
    "T1574.001": ("Hijack Execution Flow: DLL Search Order Hijacking", "Persistence"),
    "T1574.002": ("Hijack Execution Flow: DLL Side-Loading", "Persistence"),
    "T1574.007": ("Hijack Execution Flow: Path Interception by PATH Environment Variable", "Persistence"),
    "T1505":     ("Server Software Component", "Persistence"),
    "T1505.003": ("Server Software Component: Web Shell", "Persistence"),
    "T1525":     ("Implant Internal Image", "Persistence"),
    "T1053.002": ("Scheduled Task/Job: At", "Persistence"),
    # ── Privilege Escalation ──────────────────────────────────────────
    "T1548":     ("Abuse Elevation Control Mechanism", "Privilege Escalation"),
    "T1548.001": ("Abuse Elevation Control Mechanism: Setuid and Setgid", "Privilege Escalation"),
    "T1548.002": ("Abuse Elevation Control Mechanism: Bypass User Account Control", "Privilege Escalation"),
    "T1548.003": ("Abuse Elevation Control Mechanism: Sudo and Sudo Caching", "Privilege Escalation"),
    "T1134":     ("Access Token Manipulation", "Privilege Escalation"),
    "T1134.001": ("Access Token Manipulation: Token Impersonation/Theft", "Privilege Escalation"),
    "T1134.002": ("Access Token Manipulation: Create Process with Token", "Privilege Escalation"),
    "T1134.004": ("Access Token Manipulation: Parent PID Spoofing", "Privilege Escalation"),
    "T1068":     ("Exploitation for Privilege Escalation", "Privilege Escalation"),
    "T1611":     ("Escape to Host", "Privilege Escalation"),
    # ── Defense Evasion ───────────────────────────────────────────────
    "T1027":     ("Obfuscated Files or Information", "Defense Evasion"),
    "T1027.001": ("Obfuscated Files or Information: Binary Padding", "Defense Evasion"),
    "T1027.002": ("Obfuscated Files or Information: Software Packing", "Defense Evasion"),
    "T1027.003": ("Obfuscated Files or Information: Steganography", "Defense Evasion"),
    "T1027.004": ("Obfuscated Files or Information: Compile After Delivery", "Defense Evasion"),
    "T1027.005": ("Obfuscated Files or Information: Indicator Removal from Tools", "Defense Evasion"),
    "T1027.009": ("Obfuscated Files or Information: Embedded Payloads", "Defense Evasion"),
    "T1027.010": ("Obfuscated Files or Information: Command Obfuscation", "Defense Evasion"),
    "T1036":     ("Masquerading", "Defense Evasion"),
    "T1036.003": ("Masquerading: Rename System Utilities", "Defense Evasion"),
    "T1036.004": ("Masquerading: Masquerade Task or Service", "Defense Evasion"),
    "T1036.005": ("Masquerading: Match Legitimate Name or Location", "Defense Evasion"),
    "T1055":     ("Process Injection", "Defense Evasion"),
    "T1055.001": ("Process Injection: Dynamic-link Library Injection", "Defense Evasion"),
    "T1055.002": ("Process Injection: Portable Executable Injection", "Defense Evasion"),
    "T1055.003": ("Process Injection: Thread Execution Hijacking", "Defense Evasion"),
    "T1055.004": ("Process Injection: Asynchronous Procedure Call", "Defense Evasion"),
    "T1055.008": ("Process Injection: Ptrace System Calls", "Defense Evasion"),
    "T1055.009": ("Process Injection: Proc Memory", "Defense Evasion"),
    "T1055.011": ("Process Injection: Extra Window Memory Injection", "Defense Evasion"),
    "T1055.012": ("Process Injection: Process Hollowing", "Defense Evasion"),
    "T1055.013": ("Process Injection: Process Doppelgänging", "Defense Evasion"),
    "T1055.014": ("Process Injection: VDSO Hijacking", "Defense Evasion"),
    "T1070":     ("Indicator Removal", "Defense Evasion"),
    "T1070.001": ("Indicator Removal: Clear Windows Event Logs", "Defense Evasion"),
    "T1070.003": ("Indicator Removal: Clear Command History", "Defense Evasion"),
    "T1070.004": ("Indicator Removal: File Deletion", "Defense Evasion"),
    "T1070.006": ("Indicator Removal: Timestomp", "Defense Evasion"),
    "T1112":     ("Modify Registry", "Defense Evasion"),
    "T1140":     ("Deobfuscate/Decode Files or Information", "Defense Evasion"),
    "T1218":     ("System Binary Proxy Execution", "Defense Evasion"),
    "T1218.001": ("System Binary Proxy Execution: Compiled HTML File", "Defense Evasion"),
    "T1218.002": ("System Binary Proxy Execution: Control Panel", "Defense Evasion"),
    "T1218.003": ("System Binary Proxy Execution: CMSTP", "Defense Evasion"),
    "T1218.005": ("System Binary Proxy Execution: Mshta", "Defense Evasion"),
    "T1218.007": ("System Binary Proxy Execution: Msiexec", "Defense Evasion"),
    "T1218.009": ("System Binary Proxy Execution: Regsvcs/Regasm", "Defense Evasion"),
    "T1218.010": ("System Binary Proxy Execution: Regsvr32", "Defense Evasion"),
    "T1218.011": ("System Binary Proxy Execution: Rundll32", "Defense Evasion"),
    "T1218.012": ("System Binary Proxy Execution: Verclsid", "Defense Evasion"),
    "T1218.013": ("System Binary Proxy Execution: Mavinject", "Defense Evasion"),
    "T1218.014": ("System Binary Proxy Execution: MMC", "Defense Evasion"),
    "T1222":     ("File and Directory Permissions Modification", "Defense Evasion"),
    "T1497":     ("Virtualization/Sandbox Evasion", "Defense Evasion"),
    "T1497.001": ("Virtualization/Sandbox Evasion: System Checks", "Defense Evasion"),
    "T1497.002": ("Virtualization/Sandbox Evasion: User Activity Based Checks", "Defense Evasion"),
    "T1497.003": ("Virtualization/Sandbox Evasion: Time Based Evasion", "Defense Evasion"),
    "T1553":     ("Subvert Trust Controls", "Defense Evasion"),
    "T1553.002": ("Subvert Trust Controls: Code Signing", "Defense Evasion"),
    "T1553.004": ("Subvert Trust Controls: Install Root Certificate", "Defense Evasion"),
    "T1562":     ("Impair Defenses", "Defense Evasion"),
    "T1562.001": ("Impair Defenses: Disable or Modify Tools", "Defense Evasion"),
    "T1562.002": ("Impair Defenses: Disable Windows Event Logging", "Defense Evasion"),
    "T1562.004": ("Impair Defenses: Disable or Modify System Firewall", "Defense Evasion"),
    "T1562.009": ("Impair Defenses: Safe Mode Boot", "Defense Evasion"),
    "T1564":     ("Hide Artifacts", "Defense Evasion"),
    "T1564.001": ("Hide Artifacts: Hidden Files and Directories", "Defense Evasion"),
    "T1564.003": ("Hide Artifacts: Hidden Window", "Defense Evasion"),
    "T1599":     ("Network Boundary Bridging", "Defense Evasion"),
    "T1202":     ("Indirect Command Execution", "Defense Evasion"),
    "T1221":     ("Template Injection", "Defense Evasion"),
    "T1599.001": ("Network Boundary Bridging: Network Address Translation Traversal", "Defense Evasion"),
    "T1620":     ("Reflective Code Loading", "Defense Evasion"),
    # ── Credential Access ─────────────────────────────────────────────
    "T1003":     ("OS Credential Dumping", "Credential Access"),
    "T1003.001": ("OS Credential Dumping: LSASS Memory", "Credential Access"),
    "T1003.002": ("OS Credential Dumping: Security Account Manager", "Credential Access"),
    "T1003.003": ("OS Credential Dumping: NTDS", "Credential Access"),
    "T1003.004": ("OS Credential Dumping: LSA Secrets", "Credential Access"),
    "T1003.005": ("OS Credential Dumping: Cached Domain Credentials", "Credential Access"),
    "T1056":     ("Input Capture", "Credential Access"),
    "T1056.001": ("Input Capture: Keylogging", "Credential Access"),
    "T1056.002": ("Input Capture: GUI Input Capture", "Credential Access"),
    "T1110":     ("Brute Force", "Credential Access"),
    "T1539":     ("Steal Web Session Cookie", "Credential Access"),
    "T1552":     ("Unsecured Credentials", "Credential Access"),
    "T1552.001": ("Unsecured Credentials: Credentials In Files", "Credential Access"),
    "T1552.002": ("Unsecured Credentials: Credentials in Registry", "Credential Access"),
    "T1555":     ("Credentials from Password Stores", "Credential Access"),
    "T1555.003": ("Credentials from Password Stores: Credentials from Web Browsers", "Credential Access"),
    "T1558":     ("Steal or Forge Kerberos Tickets", "Credential Access"),
    "T1606":     ("Forge Web Credentials", "Credential Access"),
    # ── Discovery ─────────────────────────────────────────────────────
    "T1007":     ("System Service Discovery", "Discovery"),
    "T1010":     ("Application Window Discovery", "Discovery"),
    "T1012":     ("Query Registry", "Discovery"),
    "T1016":     ("System Network Configuration Discovery", "Discovery"),
    "T1016.001": ("System Network Configuration Discovery: Internet Connection Discovery", "Discovery"),
    "T1018":     ("Remote System Discovery", "Discovery"),
    "T1033":     ("System Owner/User Discovery", "Discovery"),
    "T1040":     ("Network Sniffing", "Discovery"),
    "T1049":     ("System Network Connections Discovery", "Discovery"),
    "T1057":     ("Process Discovery", "Discovery"),
    "T1082":     ("System Information Discovery", "Discovery"),
    "T1083":     ("File and Directory Discovery", "Discovery"),
    "T1087":     ("Account Discovery", "Discovery"),
    "T1087.001": ("Account Discovery: Local Account", "Discovery"),
    "T1087.002": ("Account Discovery: Domain Account", "Discovery"),
    "T1120":     ("Peripheral Device Discovery", "Discovery"),
    "T1124":     ("System Time Discovery", "Discovery"),
    "T1135":     ("Network Share Discovery", "Discovery"),
    "T1482":     ("Domain Trust Discovery", "Discovery"),
    "T1518":     ("Software Discovery", "Discovery"),
    "T1518.001": ("Software Discovery: Security Software Discovery", "Discovery"),
    "T1614":     ("System Location Discovery", "Discovery"),
    "T1622":     ("Debugger Evasion", "Discovery"),
    # ── Lateral Movement ─────────────────────────────────────────────
    "T1021":     ("Remote Services", "Lateral Movement"),
    "T1021.001": ("Remote Services: Remote Desktop Protocol", "Lateral Movement"),
    "T1021.002": ("Remote Services: SMB/Windows Admin Shares", "Lateral Movement"),
    "T1021.003": ("Remote Services: Distributed Component Object Model", "Lateral Movement"),
    "T1021.006": ("Remote Services: Windows Remote Management", "Lateral Movement"),
    "T1080":     ("Taint Shared Content", "Lateral Movement"),
    "T1550":     ("Use Alternate Authentication Material", "Lateral Movement"),
    "T1550.002": ("Use Alternate Authentication Material: Pass the Hash", "Lateral Movement"),
    # ── Collection ────────────────────────────────────────────────────
    "T1005":     ("Data from Local System", "Collection"),
    "T1025":     ("Data from Removable Media", "Collection"),
    "T1039":     ("Data from Network Shared Drive", "Collection"),
    "T1074":     ("Data Staged", "Collection"),
    "T1074.001": ("Data Staged: Local Data Staging", "Collection"),
    "T1113":     ("Screen Capture", "Collection"),
    "T1115":     ("Clipboard Data", "Collection"),
    "T1560":     ("Archive Collected Data", "Collection"),
    "T1560.001": ("Archive Collected Data: Archive via Utility", "Collection"),
    "T1602":     ("Data from Configuration Repository", "Collection"),
    # ── Command and Control ───────────────────────────────────────────
    "T1001":     ("Data Obfuscation", "Command and Control"),
    "T1001.001": ("Data Obfuscation: Junk Data", "Command and Control"),
    "T1001.003": ("Data Obfuscation: Protocol Impersonation", "Command and Control"),
    "T1008":     ("Fallback Channels", "Command and Control"),
    "T1071":     ("Application Layer Protocol", "Command and Control"),
    "T1071.001": ("Application Layer Protocol: Web Protocols", "Command and Control"),
    "T1071.002": ("Application Layer Protocol: File Transfer Protocols", "Command and Control"),
    "T1071.003": ("Application Layer Protocol: Mail Protocols", "Command and Control"),
    "T1071.004": ("Application Layer Protocol: DNS", "Command and Control"),
    "T1092":     ("Communication Through Removable Media", "Command and Control"),
    "T1095":     ("Non-Application Layer Protocol", "Command and Control"),
    "T1102":     ("Web Service", "Command and Control"),
    "T1102.001": ("Web Service: Dead Drop Resolver", "Command and Control"),
    "T1102.002": ("Web Service: Bidirectional Communication", "Command and Control"),
    "T1104":     ("Multi-Stage Channels", "Command and Control"),
    "T1105":     ("Ingress Tool Transfer", "Command and Control"),
    "T1132":     ("Data Encoding", "Command and Control"),
    "T1132.001": ("Data Encoding: Standard Encoding", "Command and Control"),
    "T1132.002": ("Data Encoding: Non-Standard Encoding", "Command and Control"),
    "T1219":     ("Remote Access Software", "Command and Control"),
    "T1572":     ("Protocol Tunneling", "Command and Control"),
    "T1573":     ("Encrypted Channel", "Command and Control"),
    "T1573.001": ("Encrypted Channel: Symmetric Cryptography", "Command and Control"),
    "T1573.002": ("Encrypted Channel: Asymmetric Cryptography", "Command and Control"),
    "T1568":     ("Dynamic Resolution", "Command and Control"),
    "T1568.001": ("Dynamic Resolution: Fast Flux DNS", "Command and Control"),
    "T1568.002": ("Dynamic Resolution: Domain Generation Algorithms", "Command and Control"),
    "T1568.003": ("Dynamic Resolution: DNS Calculation", "Command and Control"),
    # ── Exfiltration ─────────────────────────────────────────────────
    "T1020":     ("Automated Exfiltration", "Exfiltration"),
    "T1030":     ("Data Transfer Size Limits", "Exfiltration"),
    "T1041":     ("Exfiltration Over C2 Channel", "Exfiltration"),
    "T1048":     ("Exfiltration Over Alternative Protocol", "Exfiltration"),
    "T1048.001": ("Exfiltration Over Alternative Protocol: Exfiltration Over Symmetric Encrypted Non-C2 Protocol", "Exfiltration"),
    "T1048.002": ("Exfiltration Over Alternative Protocol: Exfiltration Over Asymmetric Encrypted Non-C2 Protocol", "Exfiltration"),
    "T1048.003": ("Exfiltration Over Alternative Protocol: Exfiltration Over Unencrypted Non-C2 Protocol", "Exfiltration"),
    "T1052":     ("Exfiltration Over Physical Medium", "Exfiltration"),
    "T1567":     ("Exfiltration Over Web Service", "Exfiltration"),
    "T1567.002": ("Exfiltration Over Web Service: Exfiltration to Cloud Storage", "Exfiltration"),
    # ── Impact ────────────────────────────────────────────────────────
    "T1485":     ("Data Destruction", "Impact"),
    "T1486":     ("Data Encrypted for Impact", "Impact"),
    "T1489":     ("Service Stop", "Impact"),
    "T1490":     ("Inhibit System Recovery", "Impact"),
    "T1491":     ("Defacement", "Impact"),
    "T1491.001": ("Defacement: Internal Defacement", "Impact"),
    "T1496":     ("Resource Hijacking", "Impact"),
    "T1498":     ("Network Denial of Service", "Impact"),
    "T1529":     ("System Shutdown/Reboot", "Impact"),
    "T1561":     ("Disk Wipe", "Impact"),
    "T1561.001": ("Disk Wipe: Disk Content Wipe", "Impact"),
    "T1561.002": ("Disk Wipe: Disk Structure Wipe", "Impact"),
}


def lookup_technique(technique_id: str) -> tuple[str, str]:
    """
    기법 ID로 (이름, 전술)을 반환합니다.

    알 수 없는 ID면 ("", "") 반환.
    """
    return _LOOKUP.get(technique_id, ("", ""))
