"""Extract Indicators of Compromise (IOCs) from dynamic analysis data.

Combines ProcMon events, PCAP results, registry diff, and process diff into a
single :class:`IOCReport` suitable for threat-intel sharing or further pivoting.

분석 도구 노이즈 필터링
-----------------------
동적 분석 중 ProcMon·tshark·SystemInformer 등 분석 도구 자체가 생성하는
파일 이벤트는 ``dropped_files`` IOC에서 자동으로 제외됩니다.
제외 기준: :data:`_ANALYSIS_TOOL_PATH_FRAGMENTS` 경로 패턴 참고.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from parsers.procmon_csv import ProcMonEvent, EventCategory
from parsers.pcap_parser import PcapResult

# RenameFile Detail 필드에서 목적지 경로 추출
# ProcMon Detail 예시: "FileName: C:\Users\victim\evil.exe, Replace If Exists: True"
_RENAME_DEST_RE = re.compile(r'FileName:\s*([^,\r\n]+)', re.IGNORECASE)


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class IOCReport:
    """All IOCs extracted from a single dynamic analysis run."""

    ip_addresses:  list[str] = field(default_factory=list)   # external IPs
    domains:       list[str] = field(default_factory=list)   # external hostnames
    dropped_files: list[str] = field(default_factory=list)   # files written by sample
    registry_keys: list[str] = field(default_factory=list)   # new/modified reg keys
    mutexes:       list[str] = field(default_factory=list)
    urls:          list[str] = field(default_factory=list)    # full HTTP URLs


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _is_private_ip(ip: str) -> bool:
    """Return True for RFC1918, loopback, and link-local addresses.

    Covers 10.x, 172.16-31.x, 192.168.x, 127.x, 169.254.x.
    """
    try:
        parts = ip.split(".")
        if len(parts) != 4:
            return False
        a, b = int(parts[0]), int(parts[1])
        if a == 10:
            return True
        if a == 172 and 16 <= b <= 31:
            return True
        if a == 192 and b == 168:
            return True
        if a == 127:
            return True
        if a == 169 and b == 254:
            return True
    except (ValueError, AttributeError):
        pass
    return False


# Noisy TLD / domain suffixes that indicate Microsoft / OS infrastructure
_NOISY_DOMAIN_SUFFIXES: tuple[str, ...] = (
    "microsoft.com",
    "windows.com",
    "windowsupdate.com",
    "akadns.net",
    "msftncsi.com",
    "msedge.net",
    "azure.com",
    "live.com",
    "office.com",
    "office365.com",
    "msn.com",
    "bing.com",
    ".local",
    ".arpa",
    "wns.windows.com",
    "trafficmanager.net",
)


def _is_noisy_domain(domain: str) -> bool:
    """Return True if *domain* is a well-known Microsoft / OS infrastructure host.

    Filters out domains ending with any suffix in :data:`_NOISY_DOMAIN_SUFFIXES`.
    """
    lower = domain.lower()
    for suffix in _NOISY_DOMAIN_SUFFIXES:
        if lower == suffix or lower.endswith("." + suffix.lstrip(".")):
            return True
    return False


# Executable / script extensions that indicate a dropped payload
_DROPPED_EXTENSIONS: frozenset[str] = frozenset({
    # PE 실행 파일
    ".exe", ".dll", ".scr", ".com", ".pif", ".sys", ".ocx", ".cpl", ".ax",
    # 스크립트
    ".bat", ".ps1", ".vbs", ".js", ".hta", ".wsf", ".jse", ".vbe", ".cmd",
    # 인스톨러 / 링크
    ".msi", ".lnk", ".url",
    # 임시 파일 (temp→exe rename 패턴)
    ".tmp",
    # 암호화 페이로드 / 설정 — DLL 사이드로딩 체인의 3번째 파일.
    # 실행 파일과 DLL 옆에 함께 떨어져 DLL 이 읽어 복호화하는 용도로 쓰인다.
    # 확장자만 보고 무해하다고 판단하면 체인의 핵심을 놓친다.
    ".dat", ".bin", ".pmt", ".enc", ".pak", ".blob", ".cfg", ".db", ".cache",
})

# WriteFile 대상: 기존 시스템 파일 쓰기는 대부분 정상 업데이트이므로 제외
_SYSTEM_PATH_PREFIXES_WRITE: tuple[str, ...] = (
    r"c:\windows\system32",
    r"c:\windows\syswow64",
    r"c:\windows\sysnative",
    r"c:\windows\winsxs",
    r"c:\windows\assembly",
    "c:\\program files\\",
    "c:\\program files (x86)\\",
)

# CreateFile+Created 대상: 새 파일 생성은 System32에서도 의심 (DLL 하이재킹 등)
# winsxs/softwaredistribution 같은 OS 내부 경로만 제외
_SYSTEM_PATH_PREFIXES_CREATE: tuple[str, ...] = (
    r"c:\windows\winsxs",
    r"c:\windows\assembly",
    r"c:\windows\softwaredistribution",
    r"c:\windows\servicing",
)

# Analysis tool path/name fragments — files whose lowercased path contains any of
# these strings are monitoring artifacts generated by the analysis environment
# itself, not by the sample under test.  Exclude them from dropped_files IOCs.
#
# 주의: 디렉터리 패턴은 반드시 일반 문자열(\\)로 이스케이프해야 함.
# raw string(r"...")의 끝에 \\를 쓰면 이중 백슬래시가 되어 실제 경로와 불일치.
_ANALYSIS_TOOL_PATH_FRAGMENTS: tuple[str, ...] = (
    "\\tools\\sysinternals\\",   # Sysinternals suite directory
    "\\tools\\systeminformer\\", # System Informer directory
    "\\tools\\processhacker\\",  # Process Hacker directory
    "\\tools\\die\\",            # Detect-It-Easy directory
    "procmon.exe",
    "procmon64.exe",
    "procexp.exe",
    "procexp64.exe",
    "tshark.exe",
    "dumpcap.exe",
    "systeminformer.exe",
    "zoomit.exe",
    "zoomit64.exe",
    "_mei",                      # PyInstaller temp DLLs (e.g. _MEI12345\*.dll)
    "hashmyfiles",
    "imhex.exe",
    "cff explorer",
    "internet_detector",
    "hollows_hunter",
    "hollows-hunter",
    "pe-sieve",
)

# Registry path fragments that indicate persistence / injection
_INTERESTING_REG_FRAGMENTS: tuple[str, ...] = (
    "run",
    "services",
    "winlogon",
    "appinit",
)

# ─ 드롭 파일 감지 기준 ─────────────────────────────────────────────────
# WriteFile  : 실제 데이터 기록 (result==SUCCESS 만 계산)
# CreateFile : OpenResult: Created 가 Detail에 있으면 신규 파일 생성
# RenameFile : temp→exe rename 패턴 (목적지 경로를 Detail에서 파싱)


def _file_extension(path: str) -> str:
    """Return the lowercased file extension from *path*, including the dot."""
    dot   = path.rfind(".")
    slash = max(path.rfind("\\"), path.rfind("/"))
    if dot > slash and dot != -1:
        return path[dot:].lower()
    return ""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def extract_iocs(
    events: list[ProcMonEvent],
    pcap: PcapResult,
    reg_diff: dict,
    proc_diff: dict,
    injection_events: "list[ProcMonEvent] | None" = None,
) -> IOCReport:
    """Extract IOCs from all dynamic analysis data sources.

    Parameters
    ----------
    events:
        Filtered ProcMon events (sample + known child PIDs).
    pcap:
        Parsed PCAP results.
    reg_diff:
        Dictionary with an ``"added"`` key containing new/modified registry
        entries observed during the run.  Each entry may be a dict with a
        ``"path"`` key, or a plain string.
    proc_diff:
        Dictionary describing process changes (reserved for future use,
        e.g. mutex extraction from proc handles).
    injection_events:
        추가 이벤트 목록 — pe-sieve/hollows-hunter로 확인된 injection 대상
        프로세스(svchost, explorer 등)의 미필터링 이벤트. filter_events 실행
        이후에 발견된 PIDs이므로 별도 전달이 필요하다.

    Returns
    -------
    IOCReport
        Deduplicated IOC report.
    """
    report = IOCReport()

    # ------------------------------------------------------------------
    # IP addresses (external only)
    # SMTP/FTP C2 서버 IP는 raw_ips에 이미 포함되지만,
    # 세션 파싱 결과에서 명시적으로 추가해 누락 방지
    # ------------------------------------------------------------------
    try:
        for ip in pcap.raw_ips:
            if not _is_private_ip(ip):
                report.ip_addresses.append(ip)
        for s in getattr(pcap, "smtp_sessions", []):
            if not _is_private_ip(s.dst_ip):
                report.ip_addresses.append(s.dst_ip)
        for s in getattr(pcap, "ftp_sessions", []):
            if not _is_private_ip(s.dst_ip):
                report.ip_addresses.append(s.dst_ip)
        report.ip_addresses = sorted(set(report.ip_addresses))
    except Exception:
        pass

    # ------------------------------------------------------------------
    # Domains (filter out MS / OS infrastructure)
    # ------------------------------------------------------------------
    try:
        for domain in pcap.raw_domains:
            if domain and not _is_noisy_domain(domain):
                report.domains.append(domain)
        report.domains = sorted(set(report.domains))
    except Exception:
        pass

    # ------------------------------------------------------------------
    # Dropped files (written/created/renamed executables & scripts)
    # ------------------------------------------------------------------
    try:
        for ev in events:
            if ev.category != EventCategory.FILE:
                continue

            path  = ev.path or ""
            lower = path.lower()
            op    = ev.operation

            # ── WriteFile: 실제 데이터 기록 ──────────────────────────────
            if op == "WriteFile":
                if ev.result != "SUCCESS":
                    continue
                ext = _file_extension(path)
                if ext not in _DROPPED_EXTENSIONS:
                    continue
                if any(lower.startswith(pfx) for pfx in _SYSTEM_PATH_PREFIXES_WRITE):
                    continue
                if any(frag in lower for frag in _ANALYSIS_TOOL_PATH_FRAGMENTS):
                    continue
                report.dropped_files.append(path)

            # ── CreateFile + OpenResult:Created: 신규 파일 생성 ──────────
            # 기존 파일 열기(읽기/덮어쓰기)와 구분하기 위해 Detail 필드 확인.
            # 메모리 맵 쓰기 등 WriteFile 이벤트가 없는 경우도 포착 가능.
            elif op == "CreateFile":
                if ev.result != "SUCCESS":
                    continue
                if "OpenResult: Created" not in (ev.detail or ""):
                    continue
                ext = _file_extension(path)
                if ext not in _DROPPED_EXTENSIONS:
                    continue
                # 신규 파일 생성은 System32에서도 의심 (DLL 하이재킹 등)
                # OS 내부 관리 경로만 제외
                if any(lower.startswith(pfx) for pfx in _SYSTEM_PATH_PREFIXES_CREATE):
                    continue
                if any(frag in lower for frag in _ANALYSIS_TOOL_PATH_FRAGMENTS):
                    continue
                report.dropped_files.append(path)

            # ── RenameFile: temp→exe rename 패턴 ─────────────────────────
            # 악성코드가 .tmp/.dat 등으로 저장 후 실행 파일로 이름 변경.
            # ProcMon Detail 예: "FileName: C:\...\evil.exe, Replace If Exists: ..."
            elif op == "RenameFile":
                if ev.result != "SUCCESS":
                    continue
                m = _RENAME_DEST_RE.search(ev.detail or "")
                if not m:
                    continue
                dest = m.group(1).strip()
                if not dest:
                    continue
                dest_lower = dest.lower()
                ext = _file_extension(dest)
                if ext not in _DROPPED_EXTENSIONS:
                    continue
                if any(frag in dest_lower for frag in _ANALYSIS_TOOL_PATH_FRAGMENTS):
                    continue
                report.dropped_files.append(dest)

        # injection_events: filter_events 이후 발견된 injection PID 이벤트
        # (svchost·explorer 등 외부 프로세스가 드롭한 파일 보완)
        for ev in (injection_events or []):
            if ev.category != EventCategory.FILE:
                continue
            path  = ev.path or ""
            lower = path.lower()
            op    = ev.operation
            if op == "WriteFile":
                if ev.result != "SUCCESS":
                    continue
                ext = _file_extension(path)
                if ext not in _DROPPED_EXTENSIONS:
                    continue
                if any(lower.startswith(pfx) for pfx in _SYSTEM_PATH_PREFIXES_WRITE):
                    continue
                if any(frag in lower for frag in _ANALYSIS_TOOL_PATH_FRAGMENTS):
                    continue
                report.dropped_files.append(path)
            elif op == "CreateFile":
                if ev.result != "SUCCESS":
                    continue
                if "OpenResult: Created" not in (ev.detail or ""):
                    continue
                ext = _file_extension(path)
                if ext not in _DROPPED_EXTENSIONS:
                    continue
                if any(lower.startswith(pfx) for pfx in _SYSTEM_PATH_PREFIXES_CREATE):
                    continue
                if any(frag in lower for frag in _ANALYSIS_TOOL_PATH_FRAGMENTS):
                    continue
                report.dropped_files.append(path)
            elif op == "RenameFile":
                if ev.result != "SUCCESS":
                    continue
                m = _RENAME_DEST_RE.search(ev.detail or "")
                if not m:
                    continue
                dest = m.group(1).strip()
                if not dest:
                    continue
                ext = _file_extension(dest)
                if ext not in _DROPPED_EXTENSIONS:
                    continue
                if any(frag in dest.lower() for frag in _ANALYSIS_TOOL_PATH_FRAGMENTS):
                    continue
                report.dropped_files.append(dest)

        report.dropped_files = list(dict.fromkeys(report.dropped_files))
    except Exception:
        pass

    # ------------------------------------------------------------------
    # Registry keys (persistence-related)
    # ------------------------------------------------------------------
    try:
        added_entries = reg_diff.get("added", [])
        for entry in added_entries:
            try:
                if isinstance(entry, dict):
                    path = entry.get("path", "")
                else:
                    path = str(entry)

                lower = path.lower()
                if any(frag in lower for frag in _INTERESTING_REG_FRAGMENTS):
                    report.registry_keys.append(path)
            except Exception:
                continue

        report.registry_keys = list(dict.fromkeys(report.registry_keys))
    except Exception:
        pass

    # ------------------------------------------------------------------
    # URLs (constructed from HTTP requests)
    # ------------------------------------------------------------------
    try:
        for req in pcap.http_requests:
            try:
                if req.host:
                    url = f"http://{req.host}{req.path or '/'}"
                    report.urls.append(url)
            except Exception:
                continue

        report.urls = list(dict.fromkeys(report.urls))
    except Exception:
        pass

    # Mutexes: not available from ProcMon CSV alone; left empty unless
    # proc_diff provides them.
    try:
        mutexes = proc_diff.get("mutexes", [])
        if mutexes:
            report.mutexes = list(dict.fromkeys(str(m) for m in mutexes))
    except Exception:
        pass

    return report
